pipeline:
  build-and-push:
    image: redpencil/plugin-docker-buildx:add-remote-builders
    settings:
      platforms: linux/amd64,linux/arm64 
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: latest
    secrets: [docker_username, docker_password, ssh_key, remote_builders]
    when:
      event: push
      branch: master
